### ISSUE TITLE
Setting the container height with contents vertically aligned

### ISSUE THREAD

**Issue by azivkovi** [Mastermindzh/react-cookie-consent#102]
When I decrease the height of the container either with CSS class or inline, the contents are no longer aligned vertically. Example in screenshot shows text going under the banner.
I had some success with adjusting line height but perhaps I am missing something obvious.

![Screenshot 2020-12-04 190550](https://user-images.githubusercontent.com/47382298/101198641-0eed6300-3664-11eb-8d2d-0fe184ae81cb.png)

**Comment by Mastermindzh** [comment]
Do you have example code (preferably a Stackblitz) so I can see what is going on? I can see very little on the provided image.

**Comment by azivkovi** [comment]
Should have included that, apologies.

https://stackblitz.com/edit/react-cookie-consent-issue-102?file=index.js

**Comment by Mastermindzh** [comment]
Thanks.

You are getting messed up results because of the default margin on the button and content.
It has a default margin of 15px all around (so the min-height of the container would be 30px+buttonheight). Because that is more than your container size it will be "wrapped" to the next line. Causing things to look wonky.

You can remove the margins to get this result:
![image](https://user-images.githubusercontent.com/4190290/101496051-917a6900-3969-11eb-9a73-f983288adf2f.png)


You can also modify the "flex-wrap" property.
Either set it to none or "default" to make sure everything stays on a single line.

This will allow you to specify a smaller size of the cookiebar without it reserving a bunch of extra room without modifying the button (and mostly ignoring the margin):
![image](https://user-images.githubusercontent.com/4190290/101495280-ab677c00-3968-11eb-98fb-398b48232a60.png)

Good luck and don't forget to star if you like the product :smile:
