### ISSUE TITLE
Update cookie value

### ISSUE THREAD

**Issue by joggienl** [Mastermindzh/react-cookie-consent#118]
Hello!

I am building a NextJS website and I am using react-cookie-consent to ask the user to accept/deny cookies. It works great!

As a new requirement I want to build a page where I allow the user to update their consent (accept/deny "toggle"). So I started to look at how to achieve that.

I could obviously grab the js-cookie const (`import { Cookies } from 'react-cookie-consent'`) grab the cookie and update the value. At the same time I was wondering whether it would be an idea to extend react-cookie-consent with that function (I can at least try to provide you with a PR for that)?

**Comment by Mastermindzh** [comment]
Sure you can try and make a PR.
We already have the getCookieConsentValue function which can get you the correct value of the cookie, we can use that in the `updateCookieConsentValue`  function. 

Be sure to update both the legacy and the new cookie though. Have a look at the current implementation for hints how to do it.

**Comment by situplastik** [comment]
In my opinion, rather to switch (it would be interesting as well) it would be better to have a function to remove the cookie (using js-cookie) & show again the bar in order to decide the new value (accepting or rejecting). The function would named `resetCookieConsent`. Studying the code, it may be necessary to update many code because the visibility of the bar is mastered by `visible` parameter...

I tried to do a PR with that or creating an `updateCookieConsentValue` function as @joggienl suggest, but I'm get stuck because both proposals need to update or use some functions/parameters defined in the own `CookieConsent` component:

- `updateCookieConsentValue` => I need to access internal `setCookie` function so as to use the same `cookieOptions`
- `resetCookieConsent` => I need to update internal `visible` state parameter in favor of showing again the bar

Any idea?

**Comment by Mastermindzh** [comment]
The best way, for now, would be to add "visible" as an optional parameter.
If it's set, adhere to what it says (either show, or not at all).
If it is undefined, use the cookie to determine a show/hide.

The rewrite to hooks (which is in 1 of the branches) means that we can't control the visibility of the component ourselves anyway and the visible parameter already has to be passed along there too.

**Comment by situplastik** [comment]
For sure @Mastermindzh :)
Where do you prefer PR? main branch or [hooks](https://github.com/Mastermindzh/react-cookie-consent/tree/feature/move-to-function-based) branch? I will make the `resetCookieConsent` exported function as well

**Comment by Mastermindzh** [comment]
main branch please :)

**Comment by Mastermindzh** [comment]
[6.4.0](https://www.npmjs.com/package/react-cookie-consent/v/6.4.0)
has been released 😄 

Thanks for the contribution!
