### ISSUE TITLE
GDPR compliance?

### ISSUE THREAD

**Issue by sjb3** [Mastermindzh/react-cookie-consent#124]
Hi Team,

I've got a quick question, I've been using your library along with ReactJS and curious to know that is it GDPR compliance?
Is there options to set up 'settings' like other paying services?

Thanx!

**Comment by Mastermindzh** [comment]
Hey @sjb3 ,

Whether it's compliant depends on your use case.
Things to look for:

- You can't set most types of cookies until someone hits "accept" (use onAccept as a trigger to set cookies)
- Not every country allows the scrollable accepts
- Some countries also need you to be open and list the used cookies, this is out of scope for the component.

As for your second question, no. This component doesn't offer per cookie settings. It asks the user a simple question: Do you allow ALL cookies or NO cookies?

Hope this helps :)

**Comment by situplastik** [comment]
We use these plugin for GDPR compliance. Before rendering any script that inject cookies we check react-cookie-consent `cookie` is accepted:

- User accepted ==> go ahead, render/load the script
- User denied ==> no render/load the script
- User didn't decide ==> no render/load the script

Besides this, in `onAccept` react-cookie-consent prop we execute the scripts as well in order to execute in the same moment that user accept cookies (to no wait to the re-render script lifecycle.

Futhermore, we made a [PR](https://github.com/Mastermindzh/react-cookie-consent/pull/125) in order to have a new prop called "visible" for forcing the visibility of the bar, usefull if you want to show again the bar if the user want to change their consent :)

**Comment by sjb3** [comment]
OK thanx.

I'm not sure if i set it correct, the thing is in local/demo server whether i click ACCEPT or REJECT the results are the same.

`const [allowCookies, setAllowCookies] = useState(false);`

`
<CookieConsent
        location="top"
        buttonText="I Accept"
        onAccept={() => {
          setAllowCookies(true);
        }}
        debug={true}
        enableDeclineButton
        declineButtonText="Reject"
        onDecline={() => {
          setAllowCookies(false);
        }}
        buttonStyle={{
          backgroundColor: "#6b944f",
          color: "#FFFFFF",
          fontFamily: "Roboto",
        }}
      >
        <p>
          We use cookies ...
        </p>
      </CookieConsent> 
`

Is there any way that I can improve this?

**Comment by situplastik** [comment]
in allowCookies, instead of inicialize with `false`, you have to check the CookieConsentValue in order to know the value when you render for first time the component. As the documentation says, the code should be similiar to:
```
const getCookieConsent = () => getCookieConsentValue()
const [allowCookies, setAllowCookies] = useState(getCookieConsent())
```
And you must put `<CookieConsent>` rendered component inside a conditional that check if `allowCookies === true`

**Comment by sjb3** [comment]
Thank you for your guidance!

What's bugging most is, when it's declined/rejected what it has to be?  What's the GDPR's saying about it?

**Comment by situplastik** [comment]
If declined/rejected, you can save the cookie with `false` value but no tracking cookie (GA, facebook, etc) must be created.

On internet there are many documentation about that... just search and spend some time and you will understand 100% how  GDPR works.

**Comment by Mastermindzh** [comment]
And the PR has merged. This was answered as well so I'm closing it. Feel free to reopen tho!
Version [6.4.0](https://www.npmjs.com/package/react-cookie-consent/v/6.4.0) has been released 😄

**Comment by simonhrmo** [comment]
Hello, I'd like to ask about GDPR compliance. 
According to GDPR there should be another button that would allow user to review/change selected consents.
Ideally, clicking it should result in opening a separate page/tab.
User would be allowed to select/deselect each of the cookie/purpose in there and then hit Accept (Accept selected only) 

Is there any way this could be worked in?
Thanks in advance

**Comment by Mastermindzh** [comment]
@simonhrmo , you can use the decline button with `onDecline()` to pop up a management screen and handle the accept/deny there :)

**Comment by simonhrmo** [comment]
@Mastermindzh Thanks for the answer :) 

Could you please help me understand a few things?
If I have multiple consents, should I use setDeclineCookie? According to documentation, it is boolean, but I would need perhaps json?
Can I have multiple decline buttons? Or if I need three buttons (accept, decline, customize), should I code them manually instead of using button&disableButton ?
Therefore, is it possible to use setDeclineCookie outside mentioned buttons - on childrens?

Thanks for your help :)

**Comment by Mastermindzh** [comment]
@simonhrmo , you should create a new issue instead of hijacking this one 😄.

You can add additional buttons with onClick listeners as much as you want.
If you want to add a customize then you will need to add that yourself.

**Comment by gaurangrshah** [comment]
I use this in my project to remain compliant, I am currently taking the following steps:

The banner manages a single cookie called app-consent. If this cookie is not set with a value of `true` the banner is shown, if it is set the banner is not shown. 

If a user clicks `I Understand` then both the app-consent cookie and all of the other cookies are are then added. 

If a user clicks `decline` then none of the additional cookies are set, but the app-consent cookie gets set with a value of `false` to ensure they are not shown the banner again until the cookie expires.

I also added a third option `manage my cookies` which opens a drawer with more granular controls.


Sharing here to share what works for me, and also for feedback in case I am missing something. 

Here's a gif demonstrating the flow:

![Kapture 2024-03-03 at 11 02 14](https://github.com/Mastermindzh/react-cookie-consent/assets/1086269/36768bce-8b0c-4ff7-8ae8-5e9b7360fa27)

**Comment by nik32** [comment]
> I also added a third option `manage my cookies` which opens a drawer with more granular controls.

Hey @gaurangrshah! Loved your implementation of the cookie banner! 

Can you guide a bit as to how you went about adding the third `manage my cookies` option? How did you get the values from the 'drawer' and integrated with this library? Any guidance would be really helpful!
