### ISSUE TITLE
Unable to show cookie consent banner after reset except after refreshing the page

### ISSUE THREAD

**Issue by AbdelrahmanKhaledAmer** [Mastermindzh/react-cookie-consent#127]
Our project has a button that when clicked triggers the `resetCookieConsentValue()` function (to allow the user to change their choice at any time).

After clicking the button however the page needs to be refreshed for the banner to show up again. (This is even the case when manually setting the `visible` prop value to `"show"`.

How can we make it so that unless it's manually closed, or the cookie consent value exists, the banner can automatically show again after the cookie consent value is reset.

**Comment by Mastermindzh** [comment]
Hey @AbdelrahmanKhaledAmer,

You can change the property "visible" to the value "VISIBLE_OPTIONS.hidden" in the accept handler, this will trigger a rerender of the bar and make sure it is hidden. On the next refresh, it will simply check the cookie again.

It is the very first property checked in the render function so it'll stop any rendering if it is set to hidden (or if the cookie exists).

You can [import the values](https://github.com/Mastermindzh/react-cookie-consent/blob/master/src/index.js#L17-L21) from the package itself.

**Comment by AbdelrahmanKhaledAmer** [comment]
I already tried that, and as I said at the top it doesn't work.

> After clicking the button however the page needs to be refreshed for the banner to show up again. (This is even the case when manually setting the `visible` prop value to `"show"`.

**Comment by abesto** [comment]
For what it's worth (and for future searchers), I came upon this issue when I wanted to give users the option to change their cookie consent settings after dismissing the banner. A hacky workaround seemed to be exactly what this issue is asking for (which is still not easy to do). Instead of this, I ended up implementing a "proper" solution for changing the cookie consent. IMHO something like this would be great to include in either this library, or a higher level one building on it (though I don't have the expertise to actually build that).

Basic idea:
* Defined constants for cookie name, and accepted / declined values
* Custom React component wrapping `CookieConsent` that controls visibility and `onAccept` / `onDecline` actions
* Custom React hook for storing updates in *both* the Redux store and the cookie, plus for exposing the value from the Redux store. This enables accurate control of both the visibility of the banner, and other components for changing cookie consent after the banner is dismissed.
* Cookie gets read into the Redux store on startup (and is not serialized with the rest of application state)

If you want to look at code: https://github.com/abesto/ams2-career/commit/99a481f4c9c375a0359fb864ab89bdb1db3d8e54
