### ISSUE TITLE
Determine if accepted on scroll

### ISSUE THREAD

**Issue by abstractvector** [Mastermindzh/react-cookie-consent#56]
It would be useful to know if the cookie consent was provided explicitly by clicking the button, or implicitly by scrolling. I figured the simplest solution would be to provide a parameter in the `onAccept` method.

For instance, if it was accepted on scroll the method could be invoked with an object:

```js
{ acceptedByScrolling: true }
```

Open to other implementations too.

If you are happy with the concept, let me know what implementation you'd prefer and I'm happy to submit a PR for it.

**Comment by Mastermindzh** [comment]
Man... My bad... I was sick when you sent this in and I forgot about it... Sorry :)

A parameter would be great, I love the object route so we can extend it in the future.  

IMO you can create a PR, I'll check it and most likely just accept it ;)
Do note that the type definitions might have to change because of this.

**Comment by abstractvector** [comment]
No worries - hope you're feeling better! I'll get onto that now and send you the PR once I'm done.
