### ISSUE TITLE
problem when used in gatsby

### ISSUE THREAD

**Issue by rburgst** [Mastermindzh/react-cookie-consent#69]
in https://github.com/Mastermindzh/react-cookie-consent/blob/master/src/index.js#L385

you are referring to a global location object. 

When I use this component in a gatsby website (during `yarn build`), this is not defined and causes a build problem.
Would it be possible to rewrite the default to be evaluated within the component?

see also https://www.gatsbyjs.org/docs/debugging-html-builds/

**Comment by Mastermindzh** [comment]
It should be possible.

I can work on it on Tuesday I think.
I'll get back to you :)

Thanks for the report.

**Comment by Luladjiev** [comment]
Same issue when used in Next.js project

**Comment by studioo** [comment]
Same issue when used Razzle

**Comment by Mastermindzh** [comment]
I will fix this tomorrow. Meanwhile, you can use version [4.1.0](https://www.npmjs.com/package/react-cookie-consent/v/4.1.0)

It is only missing the SameSite cookie fix for upcoming browser versions.

**Comment by Mastermindzh** [comment]
Should be fixed in version [5.0.1](https://www.npmjs.com/package/react-cookie-consent/v/5.0.1):

I only tested it in gatsby as that is the framework I have the most experience with:
![screencapture-localhost-8080-2020-05-26-17_16_30](https://user-images.githubusercontent.com/4190290/82918236-b6326480-9f74-11ea-9dd0-fa106340c7d1.png)

Let me know if anything else has to be fixed :)
Thanks again for the quick response peeps!

**Comment by rburgst** [comment]
seems to work like a charm! thanks a lot for your prompt support 💯

**Comment by Mastermindzh** [comment]
No problem! Enjoy using the component.
