### ISSUE TITLE
Revoke consent after accepted

### ISSUE THREAD

**Issue by rodrigo-arias** [Mastermindzh/react-cookie-consent#86]
Hi, thanks for this plugin. In your experience, what do you think is the best way to revoke consent once it has already been accepted?

**Comment by Mastermindzh** [comment]
In my opinion, you should have a clear page about what cookies are and how your site uses them.
This page can then also list how to delete a cookie (or even allow the user to do so with a button).

An example of mine can be found here: https://www.rickvanlieshout.com/cookies. 
It is not perfect (I want the user to be able to delete them as well), but I think it's a good place to start. Certainly, because it transparently lists all the cookies set on my domain.

Smashing a "notice" in the user's face with info where and how to disable them is a bit... invasive if you ask me. I have the page above linked IN the cookiebar but it's also visible on every page (it's a link in the footer).

My thoughts are basically as follows:

- User type "a" (90% of users..) doesn't care about cookies, he/she just ignores the bar and clicks accept.
- User type "b" is slightly worried about cookies and likely knows how to monitor/clear them.
- User type "c" is paranoid and hates (certain) cookies. They most likely use cookie blockers or even domain blocking to block cookie-related traffic.

I make my cookie bar as easy to ignore as possible for user a, detailed enough for user b, and I can't do anything (nor want to) for user c.

This, in my opinion, is as far as anyone should go. There's a certain responsibility on the users themselves as well.

**Comment by rodrigo-arias** [comment]
Thanks for your detailed reply. I was looking for a technical answer and I have received a global answer with which I agree.

**Comment by Mastermindzh** [comment]
I'm adding the technical details for people stumbling upon this answer: you can provide a button which executes:

`Cookie.remove('name');`
