### ISSUE TITLE
Changelog suggestion

### ISSUE THREAD

**Issue by robations** [Mastermindzh/react-cookie-consent#99]
I notice the changelog is missing any info about version 6. I also forget to add changelog entries and I use this snippet in package.json / scripts to make sure I don't miss this:

```
"preversion": "grep \"\\[$npm_package_version\\]\" CHANGELOG.md > /dev/null || ( echo 'You need to add an entry in CHANGELOG.md for this version.' && false )"
```

If you don't have entry for the version you're trying to add with npm, then the command will fail. It's worked for me reliably

I can open a PR with this change if you think this is a useful addition.

**Comment by robations** [comment]
While I'm here, are there breaking changes in 6?

**Comment by Mastermindzh** [comment]
Sorry to keep you hanging!

Yes there is a breaking change in 6.0, the "acceptByScrolling" was removed (as it is confirmed that that is no longer legal).

If you didn't use acceptByScrolling there are no breaking changes.
For details see [issue 88](https://github.com/Mastermindzh/react-cookie-consent/issues/88).


I've since taken your advice to heart and added the preversion script. I didn't know that "$npm_package_version" existed yet so I modified the older script to use it as well.

**Comment by robations** [comment]
Thanks @Mastermindzh for the update. I wasn't aware of the law change/clarification so useful to know.

Perhaps one day browsers will contain non-hostile cookie controls, instead of needing the interrupting widget. Meanwhile, thanks for your work.

**Comment by Mastermindzh** [comment]
No problem @robations,

I made this component because I didn't want any fuss on my own websites either.
In my humble opinion, the law is idiotic. There are a boatload of ways to circumvent this law with server-sided profiling that pretty much no-one will ever see. At least cookies **are** transparent if you know where to look...
